name: "Tests"

on:
  pull_request:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - main          # triggers on pushes that contain changes in main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - run: npm ci
      - run: npm test
